In [2]:
import pandas as pd

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202509/202509-divvy-tripdata.csv')
df2 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202510/202510-divvy-tripdata.csv')
df3 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202511/202511-divvy-tripdata.csv')
df4 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202512/202512-divvy-tripdata.csv')
df5 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202601/202601-divvy-tripdata.csv')
df6 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202602/202602-divvy-tripdata.csv')
df7 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202603/202603-divvy-tripdata.csv')
df8 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202604/202604-divvy-tripdata.csv')
df9 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202605/202605-divvy-tripdata.csv')
df10 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202606/202606-divvy-tripdata.csv')
df11 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202607/202607-divvy-tripdata.csv')
df12 = pd.read_csv('/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/dados_originais/202608/202608-divvy-tripdata.csv')

In [10]:
df = pd.concat(
    [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12],
    ignore_index=True
)

In [11]:
df.shape

(6115982, 13)

In [12]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,B0AD82B8A2556E7C,electric_bike,2025-09-01 12:05:13.323,2025-09-01 12:25:19.273,NaN,NaN,NaN,NaN,41.91,-87.63,41.96,-87.64,member
1,DCC4ABF0F7DCCE6A,electric_bike,2025-09-01 01:41:00.775,2025-09-01 01:48:59.228,NaN,NaN,NaN,NaN,41.95,-87.67,41.95,-87.65,member
2,C27785FFE7568433,electric_bike,2025-09-01 07:16:13.921,2025-09-01 07:39:51.831,NaN,NaN,NaN,NaN,41.94,-87.65,41.98,-87.65,member
3,812DB2D3AD2F18EB,electric_bike,2025-09-01 09:31:36.294,2025-09-01 09:49:08.022,NaN,NaN,NaN,NaN,41.98,-87.65,41.94,-87.65,member
4,61F6BD3174DC4E84,electric_bike,2025-09-26 08:51:58.069,2025-09-26 09:07:29.290,NaN,NaN,NaN,NaN,41.90,-87.69,41.87,-87.65,member

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6115982 entries, 0 to 6115981
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 606.6+ MB

In [14]:
df["started_at"] = pd.to_datetime(
    df["started_at"],
    errors="coerce",
    format="mixed"
)

df["ended_at"] = pd.to_datetime(
    df["ended_at"],
    errors="coerce",
    format="mixed"
)

In [15]:
df[["started_at", "ended_at"]].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [16]:
df[["started_at", "ended_at"]].isna().sum()

started_at    0
ended_at      0
dtype: int64

1. Quantos ride_id estão duplicados?

In [17]:
duplicados_id = df[df.duplicated(subset="ride_id", keep=False)]

print("Linhas envolvidas em IDs duplicados:", len(duplicados_id))
print("Quantidade de IDs duplicados:", duplicados_id["ride_id"].nunique())

Linhas envolvidas em IDs duplicados: 70
Quantidade de IDs duplicados: 35

In [18]:
contagem_duplicados = (
    duplicados_id["ride_id"]
    .value_counts()
    .sort_values(ascending=False)
)

contagem_duplicados

ride_id
D582320F33836B82    2
D28B306F00821227    2
E923A7ACDD4A9293    2
2038F30519CBC7E5    2
5C56F4FB55D5B5F5    2
41E2750A57535CF7    2
15521787039F37E5    2
4EBCC6DF233878B6    2
EAB7C279D822C763    2
5232F2CB3D297D55    2
82EDB771CE5282E8    2
C9050956F58561AD    2
B046AA82A096C6FA    2
3D8B4B1B10438A9F    2
10117825A92C182D    2
78D590AAA74CAE97    2
796A83D45529C7D8    2
03C5375398BE0649    2
D45C58C1A07DDA84    2
C85BE84CF8D18F6D    2
2034B29BDC8E2559    2
96EC33CC33D9FB6D    2
3767A2E3310A5B0B    2
76D09A47149E1197    2
437C637BFCE893DE    2
0612B2A21BA5E988    2
1DB04E901469FB2F    2
67C08EEA3F45893E    2
E87E123751FA42E1    2
69451215A387162E    2
47B00C2CFA51BED8    2
BD39C82BE83AED87    2
C71ACD907F4C4B61    2
4B93DFFDA6B08DE5    2
AE8BAD810DCE9D27    2
Name: count, dtype: int64

In [19]:
df = df.drop_duplicates(subset="ride_id", keep="first")

In [20]:
df.shape

(6115947, 13)

In [21]:
df["ride_id"].duplicated().sum()

np.int64(0)

2. Verificando se há outras duplicatas

In [23]:
colunas_viagem = [
    "rideable_type",
    "started_at",
    "ended_at",
    "start_station_name",
    "start_station_id",
    "end_station_name",
    "end_station_id",
    "start_lat",
    "start_lng",
    "end_lat",
    "end_lng",
    "member_casual"
]

duplicadas_sem_id = df.duplicated(
    subset=colunas_viagem,
    keep=False
)

print("Linhas potencialmente duplicadas, ignorando ride_id:",
      duplicadas_sem_id.sum())

Linhas potencialmente duplicadas, ignorando ride_id: 0

3. Auditar todos os valores nulos

In [22]:
nulos = df.isna().sum()

percentual_nulos = (nulos / len(df) * 100).round(2)

resumo_nulos = pd.DataFrame({
    "qtd_nulos": nulos,
    "percentual": percentual_nulos
})

resumo_nulos

                    qtd_nulos  percentual
ride_id                     0        0.00
rideable_type               0        0.00
started_at                  0        0.00
ended_at                    0        0.00
start_station_name    1285400       21.02
start_station_id      1285400       21.02
end_station_name      1349923       22.07
end_station_id        1349923       22.07
start_lat                   0        0.00
start_lng                   0        0.00
end_lat                  5420        0.09
end_lng                  5420        0.09
member_casual               0        0.00

In [24]:
print("Start station name nulo e ID preenchido:",
      ((df["start_station_name"].isna()) & (df["start_station_id"].notna())).sum())

print("Start station ID nulo e nome preenchido:",
      ((df["start_station_id"].isna()) & (df["start_station_name"].notna())).sum())

print("End station name nulo e ID preenchido:",
      ((df["end_station_name"].isna()) & (df["end_station_id"].notna())).sum())

print("End station ID nulo e nome preenchido:",
      ((df["end_station_id"].isna()) & (df["end_station_name"].notna())).sum())

Start station name nulo e ID preenchido: 0
Start station ID nulo e nome preenchido: 0
End station name nulo e ID preenchido: 0
End station ID nulo e nome preenchido: 0

In [25]:
print("end_lat nulo e end_lng preenchido:",
      ((df["end_lat"].isna()) & (df["end_lng"].notna())).sum())

print("end_lng nulo e end_lat preenchido:",
      ((df["end_lng"].isna()) & (df["end_lat"].notna())).sum())

print("Ambos end_lat e end_lng nulos:",
      ((df["end_lat"].isna()) & (df["end_lng"].isna())).sum())

end_lat nulo e end_lng preenchido: 0
end_lng nulo e end_lat preenchido: 0
Ambos end_lat e end_lng nulos: 5420

In [26]:
print("member_casual:")
print(df["member_casual"].value_counts(dropna=False))

print("\nrideable_type:")
print(df["rideable_type"].value_counts(dropna=False))

member_casual:
member_casual
member    3955594
casual    2160353
Name: count, dtype: int64

rideable_type:
rideable_type
electric_bike    4282129
classic_bike     1833818
Name: count, dtype: int64

4.Criando as durações das viagens

In [27]:
df["ride_length_min"] = (
    (df["ended_at"] - df["started_at"]).dt.total_seconds() / 60
)

In [28]:
df["ride_length_min"].describe()

count    6.115947e+06
mean     1.530917e+01
std      5.147282e+01
min     -5.479480e+01
25%      5.330058e+00
50%      9.263283e+00
75%      1.615772e+01
max      1.559950e+03
Name: ride_length_min, dtype: float64

5. Eliminando durações negativas

In [29]:
print("Duração negativa:", (df["ride_length_min"] < 0).sum())
print("Duração igual a zero:", (df["ride_length_min"] == 0).sum())
print("Duração <= 0:", (df["ride_length_min"] <= 0).sum())

Duração negativa: 29
Duração igual a zero: 0
Duração <= 0: 29

In [30]:
df[df["ride_length_min"] <= 0][
    ["ride_id", "started_at", "ended_at", "ride_length_min", "member_casual"]
].sort_values("ride_length_min").head(30)

,ride_id,started_at,ended_at,ride_length_min,member_casual
1601818,5740B9AA6176D32C,2025-11-02 01:59:56.801,2025-11-02 01:05:09.113,-54.794800,member
1572459,ED8C9D500F271C3D,2025-11-02 01:57:24.553,2025-11-02 01:02:44.165,-54.673133,member
1519447,222A5E8650C55311,2025-11-02 01:55:51.266,2025-11-02 01:01:50.026,-54.020667,member
1488321,985A3462DAACFFCF,2025-11-02 01:59:07.835,2025-11-02 01:05:19.214,-53.810350,member
1703749,E37AEB3E9CE2343E,2025-11-02 01:56:26.465,2025-11-02 01:03:08.183,-53.304700,member
1457310,4A659F1BB40EDBF7,2025-11-02 01:55:38.177,2025-11-02 01:04:35.315,-51.047700,casual
1508244,434E3D11ABA96891,2025-11-02 01:59:40.156,2025-11-02 01:08:51.303,-50.814217,casual
1573817,4976DE4C5F1AA516,2025-11-02 01:56:44.152,2025-11-02 01:06:51.164,-49.883133,member
1528215,83995E751A0DB5D5,2025-11-02 01:50:50.530,2025-11-02 01:01:15.026,-49.591733,member
1624634,093B3FC8E465DA4A,2025-11-02 01:52:58.523,2025-11-02 01:04:31.464,-48.450983,member
1637034,01C21B340CC1EEDA,2025-11-02 01:50:43.657,2025-11-02 01:03:13.912,-47.495750,casual
1518079,12E0A9A586A45DE3,2025-11-02 01:49:41.788,2025-11-02 01:02:30.041,-47.195783,member
1518062,9288498F5630E3AD,2025-11-02 01:49:48.360,2025-11-02 01:02:40.976,-47.123067,casual
1482863,DA5386E5759667EC,2025-11-02 01:51:31.704,2025-11-02 01:05:47.339,-45.739417,member
1638176,F87FA50B8D40FA97,2025-11-02 01:54:25.185,2025-11-02 01:10:50.859,-43.572100,casual
1596009,A66DEC9146C488BF,2025-11-02 01:50:17.559,2025-11-02 01:07:46.445,-42.518567,member
1574194,3301C8D1FF15E4CE,2025-11-02 01:58:08.316,2025-11-02 01:16:43.649,-41.411117,member
1670757,5F7692C857079901,2025-11-02 01:54:17.357,2025-11-02 01:13:50.718,-40.443983,member
1385919,5D010AFEA6850513,2025-11-02 01:52:37.475,2025-11-02 01:13:24.728,-39.212450,member
1561373,4446901DBDE0531B,2025-11-02 01:45:25.021,2025-11-02 01:08:08.134,-37.281450,casual
1387467,D1E5316AD88ECD45,2025-11-02 01:50:39.702,2025-11-02 01:14:04.164,-36.592300,casual
1404357,19386939ECD81B33,2025-11-02 01:55:34.399,2025-11-02 01:21:31.873,-34.042100,member
1598278,595AED6AB9A66E8F,2025-11-02 01:51:37.195,2025-11-02 01:18:08.912,-33.471383,member
1561269,120BC0544C3B92E4,2025-11-02 01:41:32.055,2025-11-02 01:08:10.359,-33.361600,casual
1626109,C89AFBD919D615FD,2025-11-02 01:51:49.264,2025-11-02 01:18:50.977,-32.971450,member
1635622,8BF21DA40F846779,2025-11-02 01:57:17.456,2025-11-02 01:26:23.644,-30.896867,member
1389461,3AF2F8908C9386F8,2025-11-02 01:57:57.512,2025-11-02 01:33:52.225,-24.088117,member
1621382,A61B896123C0D647,2025-11-02 01:28:03.715,2025-11-02 01:05:17.029,-22.778100,casual
1412725,083534D28DA37F72,2025-11-02 01:17:57.001,2025-11-02 01:05:27.752,-12.487483,member

In [31]:
#essas 29 viagens não são necessariamente viagens inválidas. É uma ambiguidade causada pelo horário de verão em Chicago, em 2025:
negativas = df[df["ride_length_min"] < 0]

print(negativas["started_at"].dt.date.value_counts())
print()
print(negativas["ride_length_min"].describe())

started_at
2025-11-02    29
Name: count, dtype: int64

count    29.000000
mean    -41.830155
std      10.682434
min     -54.794800
25%     -49.883133
50%     -43.572100
75%     -34.042100
max     -12.487483
Name: ride_length_min, dtype: float64

In [32]:
#Removendo:
df = df[df["ride_length_min"] > 0].copy()

df.shape

(6115918, 14)

6.Agregando

In [33]:
df.groupby("member_casual")["ride_length_min"].agg(
    quantidade="count",
    media="mean",
    mediana="median",
    minimo="min",
    maximo="max"
)

               quantidade      media    mediana    minimo       maximo
member_casual
casual            2160344  20.696474  10.864300  0.000767  1559.950183
member            3955574  12.367305   8.552958  0.000933  1559.903683

In [34]:
print("Viagens > 6h:", (df["ride_length_min"] > 360).sum())
print("Viagens > 12h:", (df["ride_length_min"] > 720).sum())
print("Viagens > 24h:", (df["ride_length_min"] > 1440).sum())
print("Maior duração:", df["ride_length_min"].max())

Viagens > 6h: 9322
Viagens > 12h: 7549
Viagens > 24h: 5302
Maior duração: 1559.9501833333334

In [35]:
df.nlargest(20, "ride_length_min")[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_length_min",
        "member_casual",
        "rideable_type"
    ]
]

,ride_id,started_at,ended_at,ride_length_min,member_casual,rideable_type
2264740,C82393BDD3070D5D,2026-03-07 16:07:09.988,2026-03-08 18:07:06.999,1559.950183,casual,classic_bike
2341901,250556580DD308BE,2026-03-07 23:51:38.812,2026-03-09 01:51:33.033,1559.903683,member,classic_bike
2338427,266FF1F3D3203623,2026-03-07 12:29:39.955,2026-03-08 14:29:33.587,1559.893867,casual,classic_bike
2342823,F2DADD2100A676E7,2026-03-07 09:43:11.203,2026-03-08 11:43:04.158,1559.882583,casual,classic_bike
2264872,EB04F9C062AAAF6A,2026-03-07 09:33:18.048,2026-03-08 11:33:09.975,1559.865450,casual,classic_bike
2336652,7CFD1B6B5319BB28,2026-03-07 12:20:32.025,2026-03-08 14:20:23.251,1559.853767,casual,classic_bike
2336655,B35EFB4539BB4B2B,2026-03-07 02:41:16.669,2026-03-08 04:41:03.312,1559.777383,casual,classic_bike
2380917,13769591C639EB0C,2026-03-07 12:45:52.881,2026-03-08 14:45:33.445,1559.676067,member,classic_bike
2220156,A679963188E41606,2026-03-07 14:40:43.466,2026-03-08 16:40:22.698,1559.653867,casual,classic_bike
2341221,FBBF2C15825C4E6F,2026-03-07 12:28:27.947,2026-03-08 14:28:06.578,1559.643850,casual,classic_bike
4866552,71576CE9479AE64C,2026-07-28 16:17:57.039,2026-07-29 17:17:55.971,1499.982200,casual,classic_bike
6030783,75A88A4A44A1EF23,2026-08-05 17:05:37.190,2026-08-06 18:05:35.867,1499.977950,member,classic_bike
99309,12C97943CCD414FD,2025-09-08 19:07:17.441,2025-09-09 20:07:16.001,1499.976000,casual,classic_bike
6026200,5B4BD76AB5869571,2026-08-22 12:14:53.294,2026-08-23 13:14:51.850,1499.975933,casual,classic_bike
3237245,734B81147A12ED6C,2026-05-27 06:19:32.497,2026-05-28 07:19:30.988,1499.974850,member,classic_bike
4278053,1CEC7F9938C112B6,2026-06-07 02:09:42.484,2026-06-08 03:09:40.916,1499.973867,casual,classic_bike
5234002,283C19C2345DA780,2026-07-26 20:22:00.572,2026-07-27 21:21:58.990,1499.973633,casual,classic_bike
1458990,A140EF9BADB5ECBD,2025-11-18 07:35:02.429,2025-11-19 08:35:00.819,1499.973167,member,classic_bike
4249598,4A513F6B8F690988,2026-06-05 01:24:31.630,2026-06-06 02:24:29.956,1499.972100,casual,classic_bike
2881353,D3DF42BAAE57C9D6,2026-04-25 09:35:57.541,2026-04-26 10:35:55.836,1499.971583,member,classic_bike

In [36]:
print("Viagens < 1 minuto:",
      (df["ride_length_min"] < 1).sum())

print("Viagens entre 1 e 60 minutos:",
      ((df["ride_length_min"] >= 1) &
       (df["ride_length_min"] <= 60)).sum())

print("Viagens entre 1h e 6h:",
      ((df["ride_length_min"] > 60) &
       (df["ride_length_min"] <= 360)).sum())

print("Viagens entre 6h e 24h:",
      ((df["ride_length_min"] > 360) &
       (df["ride_length_min"] <= 1440)).sum())

print("Viagens > 24h:",
      (df["ride_length_min"] > 1440).sum())

Viagens < 1 minuto: 158875
Viagens entre 1 e 60 minutos: 5842928
Viagens entre 1h e 6h: 104793
Viagens entre 6h e 24h: 4020
Viagens > 24h: 5302

7.Entendendo se há padrões

In [37]:
faixas = pd.cut(
    df["ride_length_min"],
    bins=[0, 1, 60, 360, 1440, float("inf")],
    labels=[
        "< 1 min",
        "1 a 60 min",
        "1 a 6 h",
        "6 a 24 h",
        "> 24 h"
    ],
    right=False
)

pd.crosstab(
    faixas,
    df["member_casual"],
    margins=True
)

member_casual     casual   member      All
ride_length_min
< 1 min            75082    83793   158875
1 a 60 min       1997575  3845353  5842928
1 a 6 h            81034    23759   104793
6 a 24 h            2413     1607     4020
> 24 h              4240     1062     5302
All              2160344  3955574  6115918

In [38]:
pd.crosstab(
    faixas,
    df["rideable_type"],
    margins=True
)

rideable_type    classic_bike  electric_bike      All
ride_length_min
< 1 min                     0         158875   158875
1 a 60 min            1767254        4075674  5842928
1 a 6 h                 57458          47335   104793
6 a 24 h                 3792            228     4020
> 24 h                   5302              0     5302
All                   1833806        4282112  6115918

In [39]:
df_comparacao = df[
    (df["ride_length_min"] >= 1) &
    (df["ride_length_min"] <= 1440)
]

print("BASE ATUAL")
display(
    df.groupby("member_casual")["ride_length_min"]
      .agg(["count", "mean", "median"])
)

print("\nBASE ENTRE 1 MINUTO E 24 HORAS")
display(
    df_comparacao.groupby("member_casual")["ride_length_min"]
                 .agg(["count", "mean", "median"])
)

BASE ATUAL

                 count       mean     median
member_casual
casual         2160344  20.696474  10.864300
member         3955574  12.367305   8.552958

BASE ENTRE 1 MINUTO E 24 HORAS

                 count       mean     median
member_casual
casual         2081022  18.416251  11.250950
member         3870719  12.219343   8.729717

8.Criando variaveis derivadas

In [40]:
df["day_of_week"] = df["started_at"].dt.day_name()

df["month"] = df["started_at"].dt.month_name()

df["hour"] = df["started_at"].dt.hour

In [41]:
df["day_of_week_num"] = df["started_at"].dt.dayofweek

df["year_month"] = df["started_at"].dt.to_period("M").astype(str)

In [42]:
df[
    [
        "started_at",
        "day_of_week",
        "day_of_week_num",
        "month",
        "year_month",
        "hour",
        "ride_length_min"
    ]
].head(10)

,started_at,day_of_week,day_of_week_num,month,year_month,hour,ride_length_min
0,2025-09-01 12:05:13.323,Monday,0,September,2025-09,12,20.099167
1,2025-09-01 01:41:00.775,Monday,0,September,2025-09,1,7.974217
2,2025-09-01 07:16:13.921,Monday,0,September,2025-09,7,23.631833
3,2025-09-01 09:31:36.294,Monday,0,September,2025-09,9,17.528800
4,2025-09-26 08:51:58.069,Friday,4,September,2025-09,8,15.520350
5,2025-09-25 19:58:47.042,Thursday,3,September,2025-09,19,16.085283
6,2025-09-26 18:47:26.836,Friday,4,September,2025-09,18,9.283417
7,2025-09-22 08:14:40.223,Monday,0,September,2025-09,8,13.000633
8,2025-09-21 22:00:37.397,Sunday,6,September,2025-09,22,3.004250
9,2025-09-21 21:31:27.110,Sunday,6,September,2025-09,21,16.587933

In [43]:
df.shape

(6115918, 19)

9.Organizar índice final

In [44]:
df = df.reset_index(drop=True)

df.shape

(6115918, 19)

In [45]:
df_powerbi = df[
    [
        "ride_id",
        "rideable_type",
        "started_at",
        "ended_at",
        "member_casual",
        "ride_length_min",
        "day_of_week",
        "day_of_week_num",
        "month",
        "year_month",
        "hour"
    ]
].copy()

df_powerbi.shape

(6115918, 11)

In [46]:
print("Duplicados:", df_powerbi["ride_id"].duplicated().sum())
print("\nNulos:")
print(df_powerbi.isna().sum())

Duplicados: 0

Nulos:
ride_id            0
rideable_type      0
started_at         0
ended_at           0
member_casual      0
ride_length_min    0
day_of_week        0
day_of_week_num    0
month              0
year_month         0
hour               0
dtype: int64

In [47]:
caminho_completo = "/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/cyclistic_limpo.csv"

df.to_csv(
    caminho_completo,
    index=False
)

print("Base completa salva.")

Base completa salva.

In [48]:
caminho_powerbi = "/content/drive/MyDrive/CursoGoogleAnalytics_2026/Estudo de Caso1/cyclistic_powerbi.csv"

df_powerbi.to_csv(
    caminho_powerbi,
    index=False,
    sep=";",
    decimal=","
)

print("Base para Power BI salva.")

Base para Power BI salva.

In [49]:
print("RESUMO DA PREPARAÇÃO DOS DADOS")
print("--------------------------------")
print("Registros originais: 6.115.982")
print("Duplicatas removidas: 35")
print("Durações negativas removidas: 29")
print("Registros finais:", len(df))
print()
print("Nulos em estações foram preservados.")
print("Viagens muito curtas e muito longas foram preservadas.")
print("Duração calculada em minutos a partir de started_at e ended_at.")
print("Variáveis criadas: ride_length_min, day_of_week, day_of_week_num, month, year_month e hour.")

RESUMO DA PREPARAÇÃO DOS DADOS
--------------------------------
Registros originais: 6.115.982
Duplicatas removidas: 35
Durações negativas removidas: 29
Registros finais: 6115918

Nulos em estações foram preservados.
Viagens muito curtas e muito longas foram preservadas.
Duração calculada em minutos a partir de started_at e ended_at.
Variáveis criadas: ride_length_min, day_of_week, day_of_week_num, month, year_month e hour.